# Site settings
author: Brad Alexander
title: #{clever_name}
header-img: img/home-bg.png
email: brad.alexander913@gmail.com
copyright_name: Brad Alexander
description: > # this means to ignore newlines until "baseurl:"
   - a Blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mug913

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
